spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/java-rest-api-test-db
      username: sa
      password:

mybatis:
  mapper-locations:
    - mappers/*.xml